language: android
jdk: oraclejdk8
sudo: required
dist: precise

env:
    global:
        - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

android:
    update_sdk: true
    components:
        - platform-tools
        - tools
        - android-28

        # Additional components
        - extra-google-m2repository
        - extra-android-m2repository

        #system images
        - sys-img-armeabi-v7a-android-21

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - yes | sdkmanager --update
    - yes | sdkmanager --licenses
    - chmod +x gradlew      #Grant permissions

    # Start creating the AVD
    - android list targets
    - android list device

script:
    - ./gradlew :app:assembleDebug --continue --stacktrace

after_failure:
    - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml